targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
          include_if_null: false
          field_rename: 'snake'
    sources:
      - $package$
      - lib/**
